-- AlterTable
ALTER TABLE `product` ADD COLUMN `mark` VARCHAR(191) NULL,
    ADD COLUMN `minOrderQuantity` INTEGER NULL DEFAULT -1,
    ADD COLUMN `model` VARCHAR(191) NULL,
    ADD COLUMN `promotion` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `promotionDiscount` DOUBLE NULL DEFAULT 10.0,
    ADD COLUMN `promotionEnd` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('AVAILABLE', 'TRANSIT', 'UPON_REQUEST') NULL DEFAULT 'AVAILABLE';
